### ISSUE TITLE
please consider semantic versioning

### ISSUE THREAD

**Issue by onlyjob** [appc/goaci#28]
Please consider assigning version numbers and tagging releases. Tags/releases
are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Thank you.

See also
- http://semver.org/
- https://en.wikipedia.org/wiki/Software_versioning

**Comment by alban** [comment]
I guess adding a git tag "0.1.0" is enough for goaci. We don't need a full release with a tarball, do we?

/cc @krnowak

**Comment by jonboulle** [comment]
Yup, a tag (and possibly corresponding bump in rkt) should be fine.

**Comment by krnowak** [comment]
Tagged a 0.1.0 - https://github.com/appc/goaci/releases/tag/v0.1.0

**Comment by onlyjob** [comment]
Thanks! :)
