### ISSUE TITLE
please add copyright statement

### ISSUE THREAD

**Issue by onlyjob** [appc/goaci#29]

**Comment by krnowak** [comment]
There is a LICENSE file already.

Do you mean a header in each source file?

**Comment by onlyjob** [comment]
Full text of the license is not the same as grant of license and copyright statement. The latter is basically a text like `Copyright 2004-2016 CoreOS Inc. <contact@email.me>` documenting copyright ownership.

You just need to follow instructions [how to apply the license](../blob/master/LICENSE#L178) from the LICENSE file itself. Headers in every file are not required.

The best place where to put [copyright statement and the grant of license](../blob/master/LICENSE#L189-L201) is [README](../blob/master/README.md).

**Comment by jonboulle** [comment]
Well, applying the header DOES apply the license, in that way, so it's sufficient, right?

**Comment by jonboulle** [comment]
Oops, accidentally did this without a PR. :no_mouth:

**Comment by onlyjob** [comment]
That'll do thanks. Perhaps there is more work maintaining headers than to include this information to README but headers could be useful if someone borrows a file from the project.
