### ISSUE TITLE
support custom GOPATHs/local packages

### ISSUE THREAD

**Issue by jonboulle** [appc/goaci#5]
Right now `goaci` pulls down a fresh copy of the specified package every time. This is better in terms of isolation and reproducibility, but inconvenient for several reasons (it means the project _must_ be built off master, and _must_ be retrieved anew every time). 

Instead it should probably just allow users to reference packages in their local `GOPATH`, optionally using the current mechanism (a clean temporary checkout).

**Comment by krnowak** [comment]
This is implemented with an option `--go-path`. If not specified, then GOPATH is set to some path in /tmp.
